=== berndhahnebach/3_gitgit/src/Tools/generateBase/generateMetaModel_Module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GenerateModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Module">
		<xs:annotation>
			<xs:documentation>This is the module root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
				<xs:element name="Dependencies" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Module" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Content">
					<xs:annotation>
						<xs:documentation>This element holds the content of the module</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="Feature" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represent a Feature in the modue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Documentation of this object</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element ref="ViewProvider" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DocObject" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represnts a Document Object in the module</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0"/>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="GuiCommand" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Creats a GuiCommand in this module</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="PreferencesPage" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:annotation>
			<xs:documentation> Defines a class property</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" type="xs:string" use="required"/>
			<xs:attribute name="StartValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Author" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Name" type="xs:string" use="required"/>
								<xs:attribute name="EMail" type="xs:string" use="required"/>
								<xs:attribute name="Licence" type="xs:string" use="optional" default="LGPL"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeveloperDocu" type="xs:string" minOccurs="0"/>
				<xs:element name="UserDocu" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ViewProvider">
		<xs:annotation>
			<xs:documentation>Defins a ViewProvider for a Object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== berndhahnebach/3_gitgit/src/Tools/generateBase/generateModel_ModuleTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
	<Module Name="GenerateTestDummy">
		<Content>
			<Feature Name="Test1">
				<Documentation><Author EMail="juergen.riegel@web.de" Name="Jürgen Riegel"/></Documentation>
				<Property Type="App::PropertyString" Name="Name"/>
				<Property Type="App::PropertyInteger" Name="Zählerchen"/>
				<Property Type="App::PropertyFloat" Name="Zählerchen"/>
			</Feature>
	    </Content>
	</Module>
</GenerateModel>
